# ===========================================
# Mini Redis Configuration
# ===========================================

# Server
port=6379
bind=127.0.0.1

# Database
database_file=redis.db

# Logging
log_level=DEBUG
log_file=redis.log

# Persistence

# Enable Append Only File
appendonly=yes

# AOF filename
appendfilename=appendonly.aof
min_appendfile_size = 64MB
growt_factor = 2
# Sync policy
# always
# everysec
# no
appendfsync=everysec

# Enable AOF rewrite
auto_aof_rewrite=yes

# Rewrite when AOF reaches this size
auto_aof_rewrite_min_size=64MB

# Rewrite when AOF grows by this percentage
auto_aof_rewrite_percentage=100

# Snapshot (RDB)
save=900 1
save=300 10
save=60 10000

# Memory
maxmemory=1GB

# Eviction policy
maxmemory-policy=noeviction

# Network
timeout=300

# Threading
worker_threads=4